/** @file exposure_map.cxx
@brief Classes specific to the exposure_map application

@author Toby Burnett

See the <a href="exposure_map_guide.html"> user's guide </a>.

$Header: /nfs/slac/g/glast/ground/cvs/map_tools/src/exposure_map/exposure_map.cxx,v 1.33 2006/11/13 18:12:46 jchiang Exp $
*/

#include "map_tools/SkyImage.h"
#include "map_tools/Exposure.h"

#include "astro/SkyDir.h"

#include "st_app/StApp.h"
#include "st_app/StAppFactory.h"
#include "st_app/AppParGroup.h"
#include "st_stream/StreamFormatter.h"
#include "st_stream/st_stream.h"

#include "tip/IFileSvc.h"
#include "tip/Table.h"
#include "facilities/Util.h"

#include <sstream>
#include <iterator> // for ostream_iterator


#include <stdexcept>

namespace {
}

using namespace map_tools;


//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/** @class RequestExposure 
@brief function class requests a point from the exposure
*/
template< class F>
class RequestExposure : public astro::SkyFunction
{
public:
    RequestExposure(const Exposure& exp, const F& aeff, double norm=1.0)
        : m_exp(exp)
        , m_aeff(aeff)
        , m_norm(norm)
    {}
    double operator()(const astro::SkyDir& s)const{
        return m_norm*m_exp(s, m_aeff);
    }
private:
    const Exposure& m_exp;
    const F& m_aeff;
    double m_norm;
};
class SelectAngle {
public:
    SelectAngle(double costh): m_costh(costh){}
    
    double operator()(double z)const{
        if( fabs(z-m_costh)<0.0001 ) return 1;
        return 0;
    }
private:
    double m_costh;
};

//~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/** @class CubeDisplayApp
@brief the exposure_map application class

*/
class CubeDisplayApp : public  st_app::StApp  {
public:
    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /** \brief Create an application object, performing initializations needed for running the application.
    */
    CubeDisplayApp()
        : st_app::StApp()
        , m_f("CubeDisplayApp", "", 2)
        , m_pars(st_app::StApp::getParGroup("cube_display")) 
    {
    }
        ~CubeDisplayApp() throw() {} // required by StApp with gcc


    //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    void run() {

        m_f.setMethod("run()");

        //prompt();

        // create the exposure, read it in from the FITS input file
        std::string infile(m_pars["infile"])
            , outfile(m_pars["outfile"])
            , table( m_pars["table"]);
        facilities::Util::expandEnvVar(&infile);
        facilities::Util::expandEnvVar(&outfile);
        m_f.info() << "Creating an Exposure object from file " << infile << std::endl;

        Exposure ex(infile, table);
#if 1 //! todo: find out how this was broken
        double total_elaspsed = ex.total();
        m_f.info() << "\ttotal elapsed time: " << total_elaspsed << std::endl;
#endif

        int layers(10); // check
        // create the image object, fill it from the exposure, write out
        std::clog << "Creating an Image, will write to file " << outfile<< std::endl;

        // extract info for image from standard pars
        double xref(m_pars["xref"]), 
               yref(m_pars["yref"]), 
               pixscale(m_pars["pixscale"]); 
        std::string coordsys(m_pars["coordsys"]), proj(m_pars["proj"]);
        bool galactic (coordsys=="GAL");
        int numxpix(m_pars["numxpix"]), 
            numypix(m_pars["numypix"]);
        double fov = numxpix==1? 180. : numxpix*pixscale;

        astro::SkyDir center(xref, yref, galactic?  astro::SkyDir::GALACTIC : astro::SkyDir::EQUATORIAL);
        SkyImage image (center, outfile, pixscale, fov, layers, proj, galactic);

        // this is what 10 bins in costh generates
        double costhbins[]={0.9975, 0.9775, 0.9375, 0.8775, 0.7975, 0.6975, 0.5775, 0.4375, 0.2775, 0.0975};
        
        for ( std::vector<double>::size_type layer = 0; layer != layers; ++layer){
            double costh ( costhbins[layer] );
            std::clog << "Generating layer " << layer << ", theta =  " << acos(costh)*180/M_PI << std::endl;

            RequestExposure<SelectAngle> req(ex, SelectAngle(costh) ); 
            image.fill(req, layer);
        }
 
    }


private:
    st_stream::StreamFormatter m_f;
    st_app::AppParGroup& m_pars;
};
// Factory which can create an instance of the class above.
st_app::StAppFactory<CubeDisplayApp> g_factory("exposure_map");

/** @page exposure_map_guide exposure_map users's Guide

 - Input: an exposure cube FITS file and an effective area function.
 - Output: an image FITS file with with multiple layers for different energies

 This application  reads an exposure cube, as generated by the 
 <a href="exposure_cube_guide.html">exposure_cube</a> application. The third dimension is bins
 in theta.
 
  It creates an exposure map, or maps, for a specific effective area function, defined by the 
  "rspfunc" parameter. Values are
  @param SIMPLE - simple linear function
  @param DC1F - DC1 parametrization for the front
  @param DC1B - DC1 parametraizatio for the back
  @param DC1FB - sum o the above

  The parameters describing the output image are 
  @param pixelsize degrees per pixel
  @param npix  number of pixels across
  @param projtype CAR for cartesian, AIT for Hammer-Aitoff, etc.


- The parameter file
 @verbinclude exposure_map.par
  Print Version 
exposure_map
Generates an exposure map, or a set of exposure maps for different energies, from a livetime cube written by gtlivetimecube. 
@verbatim
Prerequisites
Input Files: 
Livetime or Exposure cube FITS file from gtlivetimecube 
Optionally, a counts map FITS file from gtbin, for which exposure_map should match the coordinate projection and gridding.  The counts map also specifies the effective area response functions for exposure_map to use. 
Links: 

Basic FTOOL Parameter Usage 
General Parameters
  infile [file]  
    Exposure or Livetime cube input file.  
      
  cmfile [file] 
    Count map input file (NONE to determine map geometry from parameters). 
      
  outfile [file] 
    Exposure map output file name (FITS format  image). 
      
  resptype = "DC2" [string]
     Response function. Default DC2 means the sum of classA and class B   
    
  numxpix = 1 [int] 
    Size of the X axis in pixels. Default (1) for full sky
    
  numypix = 1 [int] 
    Size of the Y axis in pixels. Default (1) to copy numxpix, or full sky
    
  pixscale = 1.0 [float]  
    Image scale (in degrees/pixel).  
    
  coordsys = "CEL" [string] 
    Coordinate system, CEL or GAL. 
    
  xref = 0. [float] 
    First coordinate of image center in degrees (RA or Galactic l). (default 0) 
    
  yref = 0. [float]  
    Second coordinate of image center in degrees (DEC or Galactic b). (default 0)
    
  axisrot=0. [float] 
    Rotation angle of image axis, in degrees. (default 0)
    
  (proj = "AIT") [string] 
    Coordinate projection (AIT|ZEA|ARC|CAR|GLS|MER|NCP|SIN|STG|TAN); see Calabretta & Greisen 2002, A&A, 395, 1077 for definitions of the projections.  
    Must be AIT, ZEA or CAR for auto full sky. 
    
  emin = 30 [float]
     Start value for first energy bin (MeV); must be >=30 MeV. 
    
  emax = 200000 [float] 
    Stop value for last energy bin; must be <=200 GeV. Will use this if enumbins is 1
    
  enumbins [int] 
    Number of logarithmically uniform energy bins, defaults to 8. 
    
  (bincalc = "CENTER") [string] 
     How are energy layers computed from count map ebounds?  Options are CENTER and EDGE

    
  (filter  = no default) [string] 
    Filter expression (FTOOLS style).  
    
  (table = "Exposure")  
    Exposure cube extension. 
    
  (chatter = 2) [int] 
    Chattiness of output. 
    
  (clobber = "yes") [boolean]  
    Overwrite existing output files with new output files. 
    
  (debug = "no") [boolean] 
    Debugging mode activated. 
    
  (gui = "no") [boolean]  
    Gui mode activated. 
    
  (mode = "ql") [string] 
    Mode of automatic parameters. 

Also See
gtlivetimecube 
Basic FTOOL Parameter Usage 

--------------------------------------------------------------------------------

 

Owned by: Toby Burnett  

Generated on: Mar 16 21:53:43 2006 

Last updated by: Chuck Patterson 03/20/2006 Back to Top  

 @endverbatim
 

 

 

 
 

 

*/
