/*!
* \class Constants
*
* \brief This class defines various constants needed by Goodi.
* \author Sandhia Bansal    sandhiab@lheapop.gsfc.nasa.gov
*
*
*/

#ifndef TABLE_CONSTANTS_H
#define TABLE_CONSTANTS_H 




namespace table
{

	typedef enum {Read, Write, Reads, NEW, CREATE, RECREATE, UPDATE, READ} RWmode;

	typedef enum {Success, Failure} StatusCode;
	// ValueType definition taken From CCfits - Author Ben Dorman
	typedef enum {Tnull, Tbit, Tbyte, Tlogical, Tstring, Tushort, Tdouble, Tuint, Tint, 
		Tulong, Tlong, Tfloat, Tshort, Tcomplex, Tdblcomplex, VTbit, VTbyte, VTlogical, 
		VTushort, VTshort, VTuint, VTint, VTulong, VTlong, VTfloat, VTdouble, VTcomplex, 
		VTdblcomplex} ValueType;

	typedef enum {Ibyte, Ishort, Ilong, Ifloat, Idouble, Iushort, Iulong} ImageType;

	typedef enum {TELESCOPE, INSTRUMENT, EXTNAME, EXPOSUR, HDUCLASS, HDUCLAS1, HDUCLAS2, HDUCLAS3,
		HDUCLAS4, POISSERROR, CHANTYPE, DETCHANS, FILTER, BACKFILE, CORRFILE, RESPFILE, ANCRFILE, 
		AREASCALE, BACKSCALE, CORRSCALE, HDUVERS, TLMIN1, TLMAX1, TLMIN4, OBJECT, EQUINOX, RADECSYS, 
		DATE_OBS, DATE_END, CREATOR, ONTIME, MJDREF, START, STOP, TIMEZERO, TIMESYS, TIMEUNIT, 
		HTELAPSE, DATE, TIMEREF, TASSIGN, CLOCKAPP, GPS_OUT, ORIGIN, OBSERVER, SYSERROR, HQUALITY, 
		GROUPING, DETNAM, TDIM3, CCLS0001, CDTP0001, CCNM0001, CDES0001, CBD10001, 
		CBD20001, CBD30001, CDSD0001, CVST0001, HDUDOC, OBS_ID, PSR_COLS, MC_TRUTH, NDSKEYS,
		CTYPE1, CRPIX1, CRVAL1, CDELT1, CUNIT1, CTYPE2, CRPIX2, CRVAL2, CDELT2, CUNIT2, CROTA2,
		HISTORY}  HeaderKey;

	typedef enum {TIME, ENERGY, WEIGHT, TIMEOFDAY, ENERGYUNCERT, ZENITHANGLE, AZIMUTH, RA, DEC,
		THETA, PHI, EVENTID, CONVERSIONPOINT, CONVERSIONLAYER, RECONVER, CALIBVER, QUALITY, QUALPARAM, 
		MULT, SUBSYSFLAG, GOODCAL, VERTEX, CORE, PSFERR, CALENERGY, CALTOTRLN, GAMMAPROB, 
		ACDTILESHIT, PULSEPHASE, GEOTIME, BARYTIME, BINTIME, GEOOFFSET, BARYOFFSET, EFFAREA, SIG1, SIG2, 
		COEF, TSTART, TELAPSE, EXPOSURE, SPECNUM, CHANNEL, SPECTRUM, STATERR, SYSERR, QUALT, 
		GROUP, AREASCAL, BACKSCAL, GTISTART, GTISTOP, SCPOS, LATGEO, LONGEO, RADGEO, RAZEN, DECZEN, 
		BMCIL, LMCIL, RASCZ, DECSCZ, RASCX, DECSCX, LATMODE, LIVETIME, DEADTIME, EMIN, EMAX, NGROUP, 
		FCHAN, NCHAN, MATRIX}  DataKey;

}
#endif
